# Generated by Django 4.1 on 2022-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=12)),
                ('pcode', models.CharField(max_length=4)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
